spring:
  application:
    name: Historia Clinica Comun
  datasource:
    url: jdbc:postgresql://localhost:5432/HCC_DEV
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
server:
  port: 8081

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: 3600000 # 1 hour in milliseconds 